# This is a basic workflow to help you get started with Actions

name: Card Update

on:
  workflow_dispatch:
    inputs:
      manual:
        description: 'Executar manualmente'
        required: false
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.2.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          commit_branch: devcard
          commit_filename: devcard.png
          commit_message: "chore: update ${filename}"
