name: Atualizar Readme de Citações

on:
  workflow_dispatch:
  # Dispara o fluxo de trabalho em eventos de push ou pull request, mas apenas para o branch principal
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-readme:
    name: Atualizar README de Citações
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar README com citações
        uses: siddharth2016/quote-readme@main
        with:
          OPTION: both # padrão - ambos, pode ser um de (quote, funfact, both), se 'both' então exibirá uma citação ou um fato