# Ação do GitHub para gerar um gráfico de contribuição com uma cobra comendo suas contribuições.

# Ação do GitHub para gerar um gráfico de contribuição com uma cobra comendo suas contribuições.

name: Gerar Cobra

# Controla quando a ação será executada. Esta ação é executada a cada 6 horas.

on:
  workflow_dispatch:
    inputs:
      manual:
        description: 'Executar manualmente'
        required: true
# A sequência de execuções neste fluxo de trabalho:
jobs:
  # Este fluxo de trabalho contém uma única tarefa chamada "build"
  build:
    # O tipo de runner em que a tarefa será executada
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas que serão executadas como parte da tarefa
    steps:
      # Verifica o repositório em $GITHUB_WORKSHOP, para que sua tarefa possa acessá-lo
      - uses: actions/checkout@v2

      # Gera a cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: erickrock
          # estas próximas 2 linhas geram os arquivos em um branch chamado "output". Isso evita que o branch principal fique bagunçado.
          gif_out_path: github-contribution-grid-snake.gif
          svg_out_path: github-contribution-grid-snake.svg

      # mostra o status da build. Facilita a depuração (se houver algum problema).
      - run: git status

      # Faz o push das alterações
      - name: Fazer push das alterações
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.METRICS_TOKEN }}
          branch: main
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # o branch de saída que mencionamos acima
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
