name: Waka Readme

on:
  # Atualizações agendadas (a cada hora)
  schedule: [{ cron: "0 * * * *" }]
  # Linhas abaixo permitem executar o fluxo de trabalho manualmente e a cada commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          SECTION_NAME: waka
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "True" 
          SHOW_OS: "True"

