name: Waka Readme

on:
  schedule:
    # Runs at 0am CST
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka # Esse flag pode ser definido como qualquer string, e será o nome da seção a ser substituída no readme
          COMMIT_BY_ME: false # Esse flag pode ser definido como false para fazer o commit usando o seu nome e email
          COMMIT_MESSAGE: "Atualizado com as estatísticas de desenvolvimento" # Esse flag pode ser definido como a mensagem de commit, o padrão é "Updated with Dev Metrics"
          COMMIT_USERNAME: "ErickRock" # Esse flag pode ser definido como o nome de usuário para fazer o commit, o padrão é "readme-bot"
          COMMIT_EMAIL: "erickrock@users.noreply.github.com" # Esse flag pode ser definido como o email para fazer o commit, o padrão é "41898282+github-actions[bot]@users.noreply.github.com"
          SHOW_UPDATED_DATE: false # Esse flag pode ser definido como false para mostrar a data de atualização no final do parágrafo
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S" # Esse flag pode ser definido para colocar a data de atualização em um formato, o padrão é "%d/%m/%Y %H:%M:%S"
          SHOW_LINES_OF_CODE: false # Esse flag pode ser definido como false para mostrar as linhas de código escritas até hoje
          SHOW_TOTAL_CODE_TIME: false # Esse flag pode ser definido como False para esconder o tempo de código
          SHOW_PROFILE_VIEWS: false # Esse flag pode ser definido como False para esconder as visualizações do perfil
          SHOW_DAYS_OF_WEEK: false # Esse flag pode ser definido como False para esconder os commits feitos em diferentes dias da semana
          SHOW_LANGUAGE: false # Esse flag pode ser definido como False para esconder a linguagem de programação que você usa
          SHOW_OS: false # Esse flag pode ser definido como False para esconder os sistemas operacionais que você usa
          SHOW_PROJECTS: false # Esse flag pode ser definido como False para esconder os projetos trabalhados
          SHOW_TIMEZONE: false # Esse flag pode ser definido como False para esconder o fuso horário em que você está
          SHOW_EDITORS: false # Esse flag pode ser definido como False para esconder a lista de editores de código usados
          SHOW_LANGUAGE_PER_REPO: false # Esse flag pode ser definido como False para esconder o número de repositórios em diferentes linguagens e frameworks
          SHOW_SHORT_INFO: false # Esse flag pode ser definido como False para esconder a informação curta e divertida do usuário
          SHOW_LOC_CHART: false # Esse flag pode ser definido como False para esconder as linhas de código escritas em diferentes trimestres de diferentes anos
          IGNORED_REPOS: "" # Esse flag pode ser definido como "waka-readme-stats, my-first-repo" (apenas um exemplo) para ignorar alguns repositórios que você não quer que sejam contados
          SYMBOL_VERSION: 1 # Esse flag pode ser definido como símbolo para a barra de progresso (padrão: 1)
          DEBUG_LOGGING: false # Esse flag pode ser definido para aumentar a verbosidade da saída da ação, por padrão é igual à propriedade debug do runner interno

