name: Waka update profile Readme

on:
  # Atualizações agendadas (a cada hora)
  schedule: [{ cron: "0 * * * *" }]

  # Linhas abaixo permitem executar o fluxo de trabalho manualmente e a cada commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  update-readme:
    name: Update with anmol098/waka-readme-stats repo
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          SECTION_NAME: waka
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "Atualizado com as estatísticas de desenvolvimento"
          SHOW_UPDATED_DATE: "True"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "False"
          SYMBOL_VERSION: 2
          DEBUG_LOGGING: "True"
          
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          # Seu token do GitHub
          token: ${{ secrets.METRICS_TOKEN }}
          # Opções
          user: EricRock
          base: header, activity, community, repositories, metadata
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 0
          plugin_activity_filter: all

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
