name: Waka update profile Readme

on:
  # Atualizações agendadas (a cada hora)
  schedule: [{ cron: "0 * * * *" }]

  # Linhas abaixo permitem executar o fluxo de trabalho manualmente e a cada commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          SECTION_NAME: waka
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"

      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          # Seu token do GitHub
          token: ${{ secrets.METRICS_TOKEN }}
          # Opções
          user: erickrock
          base: header, activity, community, repositories, metadata
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: all
                    
      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

  